name: ThxBud APP

on:
  push:
    branches: [ master ]
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t naveentak/thxbudimg .
    - name: Push the Docker image
      run: docker push naveentak/thxbudimg
      
